### ISSUE TITLE
``conda install -c conda-forge conda-bash-completion'' failed.

### ISSUE THREAD

**Issue by hongyi-zhao** [tartansandal/conda-bash-completion#5]
Hi,

Based on our previously discussion, I try to install the lastest version of  conda-bash-completion from channel conda-forge, but still failed.  See the following for detail:
```

$ conda install -c conda-forge conda-bash-completion
Collecting package metadata (current_repodata.json): failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/werner/.pyenv/versions/anaconda3-4.3.0/lib/python3.6/site-packages/urllib3/connection.py", line 157, in _new_conn
        (self._dns_host, self.port), self.timeout, **extra_kw
      File "/home/werner/.pyenv/versions/anaconda3-4.3.0/lib/python3.6/site-packages/urllib3/util/connection.py", line 84, in create_connection
        raise err
      File "/home/werner/.pyenv/versions/anaconda3-4.3.0/lib/python3.6/site-packages/urllib3/util/connection.py", line 74, in create_connection
        sock.connect(sa)
    socket.timeout: timed out
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/werner/.pyenv/versions/anaconda3-4.3.0/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
        chunked=chunked,
      File "/home/werner/.pyenv/versions/anaconda3-4.3.0/lib/python3.6/site-packages/urllib3/connectionpool.py", line 376, in _make_request
        self._validate_conn(conn)
      File "/home/werner/.pyenv/versions/anaconda3-4.3.0/lib/python3.6/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
        conn.connect()
      File "/home/werner/.pyenv/versions/anaconda3-4.3.0/lib/python3.6/site-packages/urllib3/connection.py", line 334, in connect
        conn = self._new_conn()
      File "/home/werner/.pyenv/versions/anaconda3-4.3.0/lib/python3.6/site-packages/urllib3/connection.py", line 164, in _new_conn
        % (self.host, self.timeout),
    urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.VerifiedHTTPSConnection object at 0x7f6d3093efd0>, 'Connection to conda.anaconda.org timed out. (connect timeout=9.15)')
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/werner/.pyenv/versions/anaconda3-4.3.0/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
        timeout=timeout
      File "/home/werner/.pyenv/versions/anaconda3-4.3.0/lib/python3.6/site-packages/urllib3/connectionpool.py", line 760, in urlopen
        **response_kw
      File "/home/werner/.pyenv/versions/anaconda3-4.3.0/lib/python3.6/site-packages/urllib3/connectionpool.py", line 760, in urlopen
        **response_kw
      File "/home/werner/.pyenv/versions/anaconda3-4.3.0/lib/python3.6/site-packages/urllib3/connectionpool.py", line 760, in urlopen
        **response_kw
      File "/home/werner/.pyenv/versions/anaconda3-4.3.0/lib/python3.6/site-packages/urllib3/connectionpool.py", line 720, in urlopen
        method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
      File "/home/werner/.pyenv/versions/anaconda3-4.3.0/lib/python3.6/site-packages/urllib3/util/retry.py", line 436, in increment
        raise MaxRetryError(_pool, url, error or ResponseError(cause))
    urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='conda.anaconda.org', port=443): Max retries exceeded with url: /conda-forge/linux-64/current_repodata.json (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f6d3093efd0>, 'Connection to conda.anaconda.org timed out. (connect timeout=9.15)'))
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/werner/.pyenv/versions/anaconda3-4.3.0/lib/python3.6/site-packages/conda/core/subdir_data.py", line 485, in fetch_repodata_remote_request
        timeout=timeout)
      File "/home/werner/.pyenv/versions/anaconda3-4.3.0/lib/python3.6/site-packages/requests/sessions.py", line 546, in get
        return self.request('GET', url, **kwargs)
      File "/home/werner/.pyenv/versions/anaconda3-4.3.0/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
        resp = self.send(prep, **send_kwargs)
      File "/home/werner/.pyenv/versions/anaconda3-4.3.0/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
        r = adapter.send(request, **kwargs)
      File "/home/werner/.pyenv/versions/anaconda3-4.3.0/lib/python3.6/site-packages/requests/adapters.py", line 504, in send
        raise ConnectTimeout(e, request=request)
    requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='conda.anaconda.org', port=443): Max retries exceeded with url: /conda-forge/linux-64/current_repodata.json (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f6d3093efd0>, 'Connection to conda.anaconda.org timed out. (connect timeout=9.15)'))
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/werner/.pyenv/versions/anaconda3-4.3.0/lib/python3.6/site-packages/conda/exceptions.py", line 1078, in __call__
        return func(*args, **kwargs)
      File "/home/werner/.pyenv/versions/anaconda3-4.3.0/lib/python3.6/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/home/werner/.pyenv/versions/anaconda3-4.3.0/lib/python3.6/site-packages/conda/cli/conda_argparse.py", line 82, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/home/werner/.pyenv/versions/anaconda3-4.3.0/lib/python3.6/site-packages/conda/cli/main_install.py", line 20, in execute
        install(args, parser, 'install')
      File "/home/werner/.pyenv/versions/anaconda3-4.3.0/lib/python3.6/site-packages/conda/cli/install.py", line 265, in install
        should_retry_solve=(_should_retry_unfrozen or repodata_fn != repodata_fns[-1]),
      File "/home/werner/.pyenv/versions/anaconda3-4.3.0/lib/python3.6/site-packages/conda/core/solve.py", line 117, in solve_for_transaction
        should_retry_solve)
      File "/home/werner/.pyenv/versions/anaconda3-4.3.0/lib/python3.6/site-packages/conda/core/solve.py", line 158, in solve_for_diff
        force_remove, should_retry_solve)
      File "/home/werner/.pyenv/versions/anaconda3-4.3.0/lib/python3.6/site-packages/conda/core/solve.py", line 262, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "/home/werner/.pyenv/versions/anaconda3-4.3.0/lib/python3.6/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/home/werner/.pyenv/versions/anaconda3-4.3.0/lib/python3.6/site-packages/conda/core/solve.py", line 415, in _collect_all_metadata
        index, r = self._prepare(prepared_specs)
      File "/home/werner/.pyenv/versions/anaconda3-4.3.0/lib/python3.6/site-packages/conda/core/solve.py", line 1004, in _prepare
        self.subdirs, prepared_specs, self._repodata_fn)
      File "/home/werner/.pyenv/versions/anaconda3-4.3.0/lib/python3.6/site-packages/conda/core/index.py", line 229, in get_reduced_index
        repodata_fn=repodata_fn)
      File "/home/werner/.pyenv/versions/anaconda3-4.3.0/lib/python3.6/site-packages/conda/core/subdir_data.py", line 105, in query_all
        result = tuple(concat(executor.map(subdir_query, channel_urls)))
      File "/home/werner/.pyenv/versions/anaconda3-4.3.0/lib/python3.6/concurrent/futures/_base.py", line 556, in result_iterator
        yield future.result()
      File "/home/werner/.pyenv/versions/anaconda3-4.3.0/lib/python3.6/concurrent/futures/_base.py", line 405, in result
        return self.__get_result()
      File "/home/werner/.pyenv/versions/anaconda3-4.3.0/lib/python3.6/concurrent/futures/_base.py", line 357, in __get_result
        raise self._exception
      File "/home/werner/.pyenv/versions/anaconda3-4.3.0/lib/python3.6/concurrent/futures/thread.py", line 55, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/home/werner/.pyenv/versions/anaconda3-4.3.0/lib/python3.6/site-packages/conda/core/subdir_data.py", line 98, in <lambda>
        package_ref_or_match_spec))
      File "/home/werner/.pyenv/versions/anaconda3-4.3.0/lib/python3.6/site-packages/conda/core/subdir_data.py", line 110, in query
        self.load()
      File "/home/werner/.pyenv/versions/anaconda3-4.3.0/lib/python3.6/site-packages/conda/core/subdir_data.py", line 174, in load
        _internal_state = self._load()
      File "/home/werner/.pyenv/versions/anaconda3-4.3.0/lib/python3.6/site-packages/conda/core/subdir_data.py", line 248, in _load
        repodata_fn=self.repodata_fn)
      File "/home/werner/.pyenv/versions/anaconda3-4.3.0/lib/python3.6/site-packages/conda/core/subdir_data.py", line 587, in fetch_repodata_remote_request
        """) % maybe_unquote(repr(e))
      File "/home/werner/.pyenv/versions/anaconda3-4.3.0/lib/python3.6/site-packages/conda/common/url.py", line 368, in maybe_unquote
        return unquote_plus(remove_auth(url)) if url else url
      File "/home/werner/.pyenv/versions/anaconda3-4.3.0/lib/python3.6/site-packages/conda/common/url.py", line 372, in remove_auth
        url_parts = parse_url(url)._asdict()
      File "/home/werner/.pyenv/versions/anaconda3-4.3.0/lib/python3.6/site-packages/conda/_vendor/urllib3/util/url.py", line 196, in parse_url
        raise LocationParseError(url)
    conda._vendor.urllib3.exceptions.LocationParseError: Failed to parse: ConnectTimeout(MaxRetryError("HTTPSConnectionPool(host='conda.anaconda.org', port=443): Max retries exceeded with url: 

`$ /home/werner/.pyenv/versions/anaconda3-4.3.0/bin/conda install -c conda-forge conda-bash-completion`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_BACKUP_HOST=x86_64-conda_cos6-linux-gnu
        CONDA_DEFAULT_ENV=Python3
             CONDA_PREFIX=/home/werner/.pyenv/versions/anaconda3-4.3.0/envs/Python3
               CONDA_ROOT=/home/werner/.pyenv/versions/anaconda3-4.3.0
                  GOPROXY=<set>
                 INFOPATH=/home/werner/.local/texlive/2019/texmf-dist/doc/info:/usr/local/share/
                          man:/usr/local/share/info:/home/werner/.brew.git/brew.git/share/info
                  MANPATH=/home/werner/.local/texlive/2019/texmf-
                          dist/doc/man:/home/werner/.brew.git/brew.git/share/man:
                     PATH=/home/werner/.pyenv/versions/anaconda3-4.3.0/bin:/home/werner/.pyenv/l
                          ibexec:/home/werner/.pyenv/plugins/python-
                          build/bin:/home/werner/.pyenv/plugins/pyenv-
                          virtualenvwrapper/bin:/home/werner/.pyenv/plugins/pyenv-
                          virtualenv/bin:/home/werner/.pyenv/plugins/pyenv-version-
                          ext/bin:/home/werner/.pyenv/plugins/pyenv-
                          update/bin:/home/werner/.pyenv/plugins/pyenv-pip-
                          migrate/bin:/home/werner/.pyenv/plugins/pyenv-
                          doctor/bin:/home/werner/.pyenv/plugins/pyenv-virtualenv/shims:/home/we
                          rner/.pyenv/shims:/home/werner/.pyenv/bin:/home/werner/.local/texlive/
                          2019/bin/x86_64-linux:/opt/openjdk/jdk-12.0.1/bin:/opt/apache-
                          maven/apache-maven-3.6.1/bin:/home/werner/Public/lang/golang/go.git/bi
                          n:/home/werner/.local/src/neofetch.git:/home/werner/.local/src/inxi.gi
                          t:/home/werner/.brew.git/brew.git/bin:/home/werner/.brew.git/brew.git/
                          sbin:/home/werner/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:
                          /usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/werner
                          /Public/finder/fzf.git/bin:/home/werner/Public/finder/ripgrep_all/ripg
                          rep_all-0.9.2-x86_64-unknown-linux-musl:/usr/local/maui/bin
          PYENV_HOOK_PATH=/home/werner/.pyenv/pyenv.d:/usr/local/etc/pyenv.d:/etc/pyenv.d:/usr/l
                          ib/pyenv/hooks:/home/werner/.pyenv/plugins/pyenv-
                          ccache/etc/pyenv.d:/home/werner/.pyenv/plugins/pyenv-
                          virtualenv/etc/pyenv.d:/home/werner/.pyenv/plugins/pyenv-which-
                          ext/etc/pyenv.d
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
               WINDOWPATH=2

     active environment : Python3
    active env location : /home/werner/.pyenv/versions/anaconda3-4.3.0/envs/Python3
       user config file : /home/werner/.condarc
 populated config files : /home/werner/.condarc
          conda version : 4.8.0
    conda-build version : not installed
         python version : 3.6.0.final.0
       virtual packages : __glibc=2.30
       base environment : /home/werner/.pyenv/versions/anaconda3-4.3.0  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/anaconda-fusion/linux-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/noarch
          package cache : /home/werner/.pyenv/versions/anaconda3-4.3.0/pkgs
                          /home/werner/.conda/pkgs
       envs directories : /home/werner/.pyenv/versions/anaconda3-4.3.0/envs
                          /home/werner/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.0 requests/2.22.0 CPython/3.6.0 Linux/5.3.0-24-generic ubuntu/19.10 glibc/2.30
                UID:GID : 1000:1000
             netrc file : /home/werner/.netrc
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

[y/N]: 
Timeout reached. No report sent.

```

**Comment by tartansandal** [comment]
Looking through the error messages, it looks like a network issue: an inability to make an SSL connection to conda.anaconda.org. That could be a problem at your end or their end.  If its their end it should be fixed, probably by now, so try again.

**Comment by hongyi-zhao** [comment]
Thanks, it seems you are correct.
